Repository mer-sroom/moa-moa, pull requests merged in 2025-01, with the labels that each got.

#31 feat : MOA-155 add background-layout common component
  src/app/[year]/(components)/common/BackgroundLayout.tsx
  src/app/[year]/layout.tsx
  src/styles/backgroundLayout.module.css
Labels: documentation

#34 feat: MOA-72 Toast Alert Test
  package-lock.json
  package.json
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/(components)/common/Toast.tsx
  src/app/[year]/page.tsx
Labels: enhancement

#38 feat : Moa-43 add Nav bar, connect with Side bar
  public/assets/icons/nav_sidebar/friend_list_icon.svg
  public/assets/icons/nav_sidebar/moa_select_icon.svg
  public/assets/icons/nav_sidebar/mypage_icon.svg
  public/assets/icons/nav_sidebar/nav_logo.svg
  public/assets/icons/nav_sidebar/nav_notification_icon.svg
  public/assets/icons/nav_sidebar/saved_moa_icon.svg
  public/assets/icons/nav_sidebar/sent_letter_icon.svg
  public/assets/icons/nav_sidebar/sidebar_copyright.svg
  src/app/[year]/(components)/common/Navbar.tsx
  src/app/[year]/(components)/common/Sidebar.tsx
  src/app/[year]/layout.tsx
  src/styles/Sidebar.module.css
  src/styles/backgroundLayout.module.css
  src/styles/globals.css
  src/styles/navbar.module.css
  src/types/sideBar.ts
Labels: documentation, enhancement, good first issue

#41 feat : Edit Modal component(MOA-157), Add Notification Modal(MOA-71)
  public/assets/icons/modal_X_btn.svg
  public/assets/icons/notification/mock_user_profile.jpg
  public/assets/icons/notification/notification_moa_cat.svg
  public/assets/icons/notification/notification_no_btn.svg
  public/assets/icons/notification/notification_yes_btn.svg
  src/app/[year]/(components)/common/Modal.tsx
  src/app/[year]/notification/(components)/NotificationContent.tsx
  src/app/[year]/notification/(components)/data.ts
  src/app/[year]/notification/page.tsx
  src/styles/globals.css
  src/styles/modal.module.css
  src/styles/notification.module.css
Labels: documentation, enhancement, good first issue

#42 fix : Moa-159 sidebar bug fixed/add login-btn for no session / notification modal
  public/assets/icons/sidebar_login_btn.svg
  src/app/[year]/(components)/common/Sidebar.tsx
  src/app/[year]/notification/(components)/NotificationContent.tsx
  src/app/[year]/notification/page.tsx
  src/styles/Sidebar.module.css
  src/styles/modal.module.css
  src/styles/notification.module.css
  src/types/sideBar.ts
Labels: enhancement
