Repository mer-sroom/moa-moa, pull requests merged in 2025-03, with the labels that each got.

#53 feat : Moa-165 Connect Mymoa/Notification with DB, delete mock data
  public/assets/default_img.png
  public/assets/icons/add_friend.svg
  public/assets/icons/pen.svg
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/(components)/common/Modal.tsx
  src/app/[year]/moa/mockData.ts
  src/app/[year]/moa/mymoa/(components)/HandleAddFriend.tsx
  src/app/[year]/moa/mymoa/(components)/LetterGrid.tsx
  src/app/[year]/moa/mymoa/(components)/LetterItem.tsx
  src/app/[year]/moa/mymoa/(components)/MailBox.tsx
  src/app/[year]/moa/mymoa/(components)/PaginatedLetterGrid.tsx
  src/app/[year]/moa/mymoa/(components)/Title.tsx
  src/app/[year]/moa/mymoa/[id]/api/route.ts
  src/app/[year]/moa/mymoa/[id]/page.tsx
  src/app/[year]/moa/select-moa/[friendId]/page.tsx
  src/app/[year]/moa/select-moa/page.tsx
  src/app/[year]/notification/(components)/NotificationContent.tsx
  src/app/[year]/notification/data.ts
  src/app/[year]/notification/page.tsx
  src/app/api/friendlist/route.ts
  src/app/api/notification/route.ts
  src/app/api/user/[id]/nickname/route.ts
  src/lib/api/user.ts
  src/styles/mymoa.module.css
  src/styles/notification.module.css
  src/styles/pagination.module.css
  src/types/moabox.ts
  src/types/notification.ts
Labels: documentation, enhancement, good first issue

#54 feat: mypage-logout
  public/assets/icons/jump-arrow.svg
  public/assets/icons/spotify.svg
  src/app/[year]/mypage/page.tsx
  src/styles/mypage.module.css
Labels: enhancement

#55 feat: Moa-77 Add letter modal feature(including Spotify) and business logic component
  prisma/migrations/20250210013023_add_image_tables/migration.sql
  prisma/migrations/20250312101911_update_letter_model/migration.sql
  prisma/schema.prisma
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/(components)/common/Modal.tsx
  src/app/[year]/(components)/common/Skeleton.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/HandleAddFriend.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/HandleWriteLetter.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/OpenLetter.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/OpenShareLinkModal.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/PaginatedLetterGrid.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/ShareLinkContent.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/LetterGrid.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/LetterItem.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/LetterModal.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/MailBox.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/SpotifyWithDelay.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/Title.tsx
  src/app/[year]/moa/mymoa/(components)/LetterModal.tsx
  src/app/[year]/moa/mymoa/(components)/OpenLetter.tsx
  src/app/[year]/moa/mymoa/[id]/layout.tsx
  src/app/[year]/moa/mymoa/[id]/page.tsx
  src/app/api/letter/[letterId]/route.ts
  src/contexts/LetterModalContext.tsx
  src/hooks/useLetterCache.ts
  src/styles/LetterModal.module.css
  src/styles/Skeleton.module.css
  src/styles/mymoa.module.css
  src/types/moabox.ts
Labels: documentation, enhancement
