Repository mer-sroom/moa-moa, pull requests merged in 2025-05, with the labels that each got.

#62 feat : MOA-55 Sent Letter Page addition
  public/assets/icons/sentLetterIcon.svg
  src/app/[year]/(components)/common/Sidebar.tsx
  src/app/[year]/layout.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/(letter-features)/OpenLetter.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/LetterModal.tsx
  src/app/[year]/moa/select-moa/[friendId]/page.tsx
  src/app/[year]/sent-letter/(components)/OpenSentLetter.tsx
  src/app/[year]/sent-letter/[id]/layout.tsx
  src/app/[year]/sent-letter/[id]/page.tsx
  src/app/[year]/sent-letter/page.tsx
  src/app/api/letter/[letterId]/route.ts
  src/app/api/notification/friend-request/route.ts
  src/app/api/notification/route.ts
  src/contexts/LetterCacheContext.tsx
  src/hooks/useLetterCache.ts
  src/lib/sentLetter.ts
  src/styles/LetterModal.module.css
  src/styles/SentLetter.module.css
  src/styles/notification.module.css
  src/types/sent-letter.d.ts
Labels: documentation, enhancement

#63 feat: MOA-106 "create moa" layout, page rendering, button rendering
  package-lock.json
  package.json
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/(create)/(components)/Calendar.tsx
  src/app/[year]/(create)/(components)/DotNav.tsx
  src/app/[year]/(create)/(components)/ToggleButton.tsx
  src/app/[year]/(create)/create-moa/page.tsx
  src/app/[year]/(create)/create-moa/step1.tsx
  src/app/[year]/(create)/create-moa/step2.tsx
  src/app/[year]/(create)/create-moa/step3.tsx
  src/app/[year]/(create)/create-moa/step4.tsx
  src/app/[year]/(create)/create-moa/step5.tsx
  src/styles/createMoa.module.css
  src/styles/dotnav.module.css
  src/styles/toggleButton.module.css
  src/types/createMoa.ts
Labels: enhancement

#65 Moa 167 dot navbar
  package-lock.json
  src/app/[year]/(create)/(components)/DotNav.tsx
  src/app/[year]/(create)/create-letter/page.tsx
  src/app/[year]/(create)/create-letter/step2.tsx
  src/app/[year]/(create)/create-letter/step5.tsx
  src/app/[year]/(create)/create-letter/step6.tsx
  src/app/[year]/(create)/create-moa/page.tsx
  src/styles/dotnav.module.css
  src/types/createMoa.ts
Labels: enhancement

#66 file : integrate button component for create-letter flow and change css setting for common Button Component
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/(create)/create-letter/page.tsx
  src/app/[year]/(create)/create-letter/step1.tsx
  src/app/[year]/(create)/create-letter/step2.tsx
  src/app/[year]/(create)/create-letter/step3.tsx
  src/app/[year]/(create)/create-letter/step4.tsx
  src/app/[year]/(create)/create-letter/step5.tsx
Labels: documentation

#67 feat: Createletter info
  public/assets/icons/create_letter/create-letter.svg
  public/assets/icons/create_letter/create-record.svg
  src/app/[year]/(create)/(components)/DotNav.tsx
  src/app/[year]/(create)/(components)/ToggleButton.tsx
  src/app/[year]/(create)/create-letter/page.tsx
  src/app/[year]/(create)/create-letter/step1.tsx
  src/app/[year]/(create)/create-letter/step3.tsx
  src/app/[year]/(create)/create-letter/step4.tsx
  src/app/[year]/(create)/create-moa/page.tsx
  src/app/api/user/[id]/delete/route.ts
  src/styles/createLetter.module.css
  src/styles/dotnav.module.css
  src/types/createMoa.ts
Labels: documentation, good first issue

#68 feat : Moa-114 add create-letter step3 page UI
  src/app/[year]/(create)/(components)/LetterPaperCarousel.tsx
  src/app/[year]/(create)/create-letter/[id]/page.tsx
  src/app/[year]/(create)/create-letter/[id]/step1.tsx
  src/app/[year]/(create)/create-letter/[id]/step2.tsx
  src/app/[year]/(create)/create-letter/[id]/step3.tsx
  src/app/[year]/(create)/create-letter/[id]/step4.tsx
  src/app/[year]/(create)/create-letter/[id]/step5.tsx
  src/app/[year]/(create)/create-letter/[id]/step6.tsx
  src/app/[year]/(create)/create-letter/page.tsx
  src/app/[year]/(create)/create-letter/step3.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/HandleWriteLetter.tsx
  src/app/[year]/moa/mymoa/[id]/page.tsx
  src/styles/CreateLetterStep3.module.css
  src/styles/dotnav.module.css
  src/types/createLetter.ts
Labels: documentation, enhancement

#69 Moa 104 create guide page
  public/assets/icons/createmoa_step1.svg
  public/assets/icons/createmoa_step5.svg
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/(create)/(components)/SelectModal.tsx
  src/app/[year]/(create)/create-moa/page.tsx
  src/app/[year]/(create)/create-moa/step1.tsx
  src/app/[year]/(create)/create-moa/step2.tsx
  src/app/[year]/(create)/create-moa/step3.tsx
  src/app/[year]/(create)/create-moa/step4.tsx
  src/app/[year]/(create)/create-moa/step5.tsx
  src/styles/SelectModal.module.css
  src/styles/createMoa.module.css
  src/styles/dotnav.module.css
  src/styles/toggleButton.module.css
  src/types/createMoa.ts
Labels: enhancement, help wanted

#70 Moa 104 create guide page
  src/app/[year]/(create)/create-moa/step4.tsx
  src/styles/SelectModal.module.css
  src/styles/createMoa.module.css
Labels: documentation

#72 file : add font + change css to responsive (select-moa)
  src/app/[year]/(components)/common/Button.tsx
  src/app/[year]/moa/mymoa/[id]/page.tsx
  src/app/[year]/moa/select-moa/(components)/SelectCarousel.tsx
  src/app/[year]/moa/select-moa/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/fonts/PretendardVariable.woff2
  src/styles/CreateLetterStep3.module.css
  src/styles/SentLetter.module.css
  src/styles/selectMoa.module.css
Labels: documentation

#74 feat : MOA-16 - 3 Add 404 page
  public/assets/moamoa_paper_texture.jpg
  public/assets/service-imgs/404img.svg
  src/app/[year]/(components)/not-found.tsx
  src/app/[year]/friendlist/page.tsx
  src/app/[year]/moa/mymoa/(components)/(features)/ShareLinkContent.tsx
  src/app/[year]/moa/mymoa/[id]/page.tsx
  src/app/[year]/moa/select-moa/[friendId]/page.tsx
  src/app/[year]/notification/page.tsx
  src/app/[year]/saved-moa/[id]/page.tsx
  src/app/[year]/sent-letter/[id]/page.tsx
  src/app/not-found.tsx
  src/styles/404.module.css
Labels: documentation, enhancement
