Repository mer-sroom/moa-moa, pull requests merged in 2025-06, with the labels that each got.

#79 Create moa step 3 - friend select modal mobile view
  package-lock.json
  package.json
  src/app/[year]/(components)/common/Modal.tsx
  src/app/[year]/(create)/(components)/SelectModal.tsx
  src/app/[year]/(create)/create-moa/step3.tsx
  src/styles/SelectModal.module.css
  src/styles/createMoa.module.css
  src/styles/modal.module.css
Labels: documentation

#80 feat: Moa-131 create letter step4
  public/assets/icons/create_letter/moa_record.svg
  src/app/[year]/(create)/(components)/MusicSelect.tsx
  src/app/[year]/(create)/create-letter/[id]/step4.tsx
  src/styles/MusicSelect.module.css
  src/styles/create-letter/CreateLetterStep4.module.css
  src/styles/createLetter.module.css
  src/styles/modal.module.css
Labels: enhancement, help wanted

#85 feat: create moa step 3, select modal friend state data edit
  src/app/[year]/(create)/(components)/SelectModal.tsx
  src/app/[year]/(create)/create-moa/step3.tsx
  src/styles/SelectModal.module.css
  src/styles/modal.module.css
  src/types/createMoa.ts
Labels: documentation

#86 feat: Add background image to BackgroundLayout.tsx, edit saved-moa, sent-letter page scroll
  src/app/[year]/(components)/common/BackgroundLayout.tsx
  src/app/[year]/saved-moa/[id]/layout.tsx
  src/app/[year]/saved-moa/[id]/page.tsx
  src/app/[year]/sent-letter/[id]/page.tsx
  src/styles/SavedMoa.module.css
  src/styles/SentLetter.module.css
  src/styles/selectMoa.module.css
Labels: documentation, problem solved

#89 Create moa backend
  prisma/migrations/20250610070451_add_decoration_type/migration.sql
  prisma/migrations/20250611130308_add_moa_decoration_design/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app/[year]/(create)/(components)/Calendar.tsx
  src/app/[year]/(create)/create-moa/step2.tsx
  src/app/[year]/(create)/create-moa/step3.tsx
  src/app/[year]/moa/select-moa/(components)/SelectCarousel.tsx
  src/app/[year]/moa/select-moa/page.tsx
  src/app/api/moa-box/route.ts
  src/contexts/CreateMoaContext.tsx
  src/lib/decoMap.ts
  src/styles/selectMoa.module.css
  src/types/moaBoxRequest.ts
  src/types/moabox.ts
Labels: documentation

#90 feat: add guide modal (coach marks modal) with image
  public/assets/service-imgs/guide/create_letter.png
  public/assets/service-imgs/guide/create_moa_step4.png
  public/assets/service-imgs/guide/friend_moa.png
  public/assets/service-imgs/guide/my_moa.png
  src/app/[year]/(components)/common/GuideModal.tsx
Labels: documentation, enhancement

#91 feat : Moa-16 add img for create-moa step 1, integrate css codes for step 1,3,4,5
  public/assets/icons/create_moa/step1_img.svg
  public/assets/icons/createmoa_step1.svg
  public/assets/moamoa_paper_texture.jpg
  public/assets/service-imgs/icons/boing.svg
  public/assets/service-imgs/icons/dot_spark.svg
  src/app/[year]/(create)/create-letter/[id]/step1.tsx
  src/app/[year]/(create)/create-moa/step1.tsx
  src/app/[year]/(create)/create-moa/step3.tsx
  src/app/[year]/(create)/create-moa/step4.tsx
  src/app/[year]/(create)/create-moa/step5.tsx
  src/styles/create-letter/createLetter.module.css
  src/styles/create-moa/createMoa.module.css
  src/styles/globals.css
Labels: documentation

#92 design: mypage alert modify
  src/app/[year]/mypage/page.tsx
Labels: enhancement, help wanted

#94 feat : MOA-16 integrate css for create-moa step 1,5 and complete create-moa step 5
  public/assets/icons/create_moa/step5_complete_img.svg
  public/assets/icons/createmoa_step5.svg
  public/assets/service-imgs/icons/boing_pink.svg
  public/assets/service-imgs/icons/twinkle.svg
  src/app/[year]/(create)/create-moa/Layout.tsx
  src/app/[year]/(create)/create-moa/page.tsx
  src/app/[year]/(create)/create-moa/step1.tsx
  src/app/[year]/(create)/create-moa/step5.tsx
  src/styles/create-moa/createMoa.module.css
Labels: documentation, enhancement

#95 feat: apply Guide Modal components
  src/app/[year]/(create)/create-letter/[id]/step2.tsx
  src/app/[year]/(create)/create-moa/step4.tsx
  src/app/[year]/moa/mymoa/[id]/(components)/GuideModalMiddle.tsx
  src/app/[year]/moa/mymoa/[id]/page.tsx
Labels: enhancement

#97 my moa UI media query & error fix
  src/app/[year]/(create)/create-moa/step4.tsx
  src/app/[year]/moa/mymoa/(components)/(ui)/GuideModalMiddle.tsx
  src/app/[year]/moa/mymoa/[id]/page.tsx
  src/styles/create-moa/createMoa.module.css
  src/styles/mymoa.module.css
Labels: documentation
